name: Pin
version: '${project.version}'
main: jp.houlab.mochidsuki.pin.Pin
api-version: '1.20'

softdepend: [ ProtocolLib ]
loadbefore:
  - MochidsukiFPSItems


commands:
  pin:
    aliases: [cp]
    description: BRC管理コマンド
    permission: pin.command.pin
    permission-message: Permission denied
    usage: gr reload